### ISSUE TITLE
I face problem

### ISSUE THREAD

**Issue by lovebdsobuj** [mpaiva/material-resume#6]
Step 1 and Step 2 is done, But Step 3 give me error. 

H:\Development\NodeJS\material-resume>gulp
H:\Development\NodeJS\material-resume\node_modules\gulp-sass\node_modules\node-s
ass\lib\index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?
');
    ^

Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (H:\Development\NodeJS\material-resume\node_modules\gulp-sass\
node_modules\node-sass\lib\index.js:22:11)
    at Object.<anonymous> (H:\Development\NodeJS\material-resume\node_modules\gu
lp-sass\node_modules\node-sass\lib\index.js:188:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (H:\Development\NodeJS\material-resume\node_modules\gu
lp-sass\index.js:3:17)
    at Module._compile (module.js:435:26)

H:\Development\NodeJS\material-resume> 

---

I re-install node modules, but got same message.

Please help me.

**Comment by lovebdsobuj** [comment]
## I solved this problem by following these command line.

1st 
npm uninstall gulp-sass --save-dev
and then
npm install gulp-sass --save-dev
and then
npm uninstall node-sasss
adn then
npm install node-sass
