### ISSUE TITLE
I face a problem about fs

### ISSUE THREAD

**Issue by Louis-Jin** [mpaiva/material-resume#9]
[12:54:31] 'jade' errored after 267 μs
[12:54:31] ReferenceError: fs is not defined
    at Gulp.<anonymous> (/Users/jindingguang/Documents/material-resume-master/gulpfile.js:41:29)
    at module.exports (/Users/jindingguang/Documents/material-resume-master/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/jindingguang/Documents/material-resume-master/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/jindingguang/Documents/material-resume-master/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/jindingguang/Documents/material-resume-master/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)

**Comment by Louis-Jin** [comment]
I solved this by adding the following line in gulpfile.js
var fs         = require('fs');

**Comment by mpaiva** [comment]
Thanks!
